### ISSUE TITLE
Settings -> Excluded directories not working

### ISSUE THREAD

**Issue by scrapix** [jlesage/docker-video-duplicate-finder#3] opened 2023-02-12 18:42 UTC
Adding a directory to excluded does not work. Anything I try to add to exclusions, appears in the included list. Works in the non-dockerized version very well

**Comment by jlesage** [comment] 2023-02-12 20:41
> Works in the non-dockerized version very well

Using the version from which date ?

I will update the container to the latest commit.  I see the container is missing the following change that has been made 5 days ago: https://github.com/0x90d/videoduplicatefinder/commit/73d33ed4419b09702ee23d16beb9189077776e60.

**Comment by jlesage** [comment] 2023-02-12 20:54
Let me know if the latest image is better.

**Comment by Maltragor** [comment] 2023-02-14 18:31
The bug occurred at 0x90d/videoduplicatefinder@490c40ca in MainWindowVM.cs

```diff
public ReactiveCommand<Unit, Unit> AddBlacklistToListCommand => ReactiveCommand.CreateFromTask(async () => {
-	var result = await new OpenFolderDialog {
-		Title = "Select folder"
-	}.ShowAsync(ApplicationHelpers.MainWindow);
-	if (string.IsNullOrEmpty(result)) return;
-	if (!SettingsFile.Instance.Blacklists.Contains(result))
-		SettingsFile.Instance.Blacklists.Add(result);
+	var result = await ApplicationHelpers.MainWindow.StorageProvider.OpenFolderPickerAsync(
+		new FolderPickerOpenOptions() {
+			AllowMultiple = true,
+			Title = "Select folder"
+		});
+
+	if (result == null || result.Count == 0) return;
+	foreach (var item in result) {
+		item.TryGetUri(out Uri? path);
+		if (!SettingsFile.Instance.Includes.Contains(path!.LocalPath))
+			SettingsFile.Instance.Includes.Add(path.LocalPath);
+	}
});
```
and still exists but was moved to MainWindowVM_Settings.cs

**Comment by jlesage** [comment] 2023-02-14 18:39
Ok I see, the issue is not specific to this container.  It also exists with the latest version from the original project.

**Comment by jlesage** [comment] 2023-02-14 18:56
I created a PR for the issue: https://github.com/0x90d/videoduplicatefinder/pull/399

**Comment by jlesage** [comment] 2023-02-17 12:03
Fixed with latest image.

**Closed by jlesage** 2023-02-17 12:03 UTC
